services:
  - type: web
    name: erp-stock-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: DATABASE_URL
        fromDatabase:
          name: erp-stock-db
          property: connectionString

databases:
  - name: erp-stock-db
    plan: free
    databaseName: posdb
    user: posuser
